In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(type(arr))
lst = [1,2,3,4,5]
print(type(lst))

<class 'numpy.ndarray'>
<class 'list'>


In [3]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [4]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [5]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [6]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [7]:
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])


In [8]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr2.shape

(2, 3)

In [11]:
arr2.ndim

2

In [12]:
arr2.size

6

In [15]:
arr2[1,0]

np.int64(4)

In [16]:
 x = np.arange(12)
 x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
x.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
x[::2]

array([ 0,  2,  4,  6,  8, 10])

In [21]:
x = x.reshape(3,4)
x[:2, :2]

array([[0, 1],
       [4, 5]])

In [24]:
ages = np.array([18, 21, 25, 17, 30])
adults = ages[ages>=18]

In [26]:
adults

array([18, 21, 25, 30])

In [5]:
import numpy as np
X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(X + np.array([10, 20, 30]))


[[11 22 33]
 [14 25 36]]


In [7]:
scores = np.array([70, 80, 90])
bonus = 5
final_scores = scores + bonus
print(final_scores)


[75 85 95]


Aggreations & Axis 

In [9]:
a = np.array([1,2,3,4,5,])


In [12]:
print(a.min())
print(a.sum())
print(a.mean())
print(a.std())
print(a.max())



1
15
3.0
1.4142135623730951
5


In [13]:
X = np.array([
    [10, 20, 30],
    [40, 50, 60]
])



In [15]:
print(X.sum(axis=1))

[ 60 150]


Linear Algrebra with Numpy

In [16]:
print(X.T)

[[10 40]
 [20 50]
 [30 60]]


In [17]:
np.random.randint(1,10,4)

array([9, 8, 9, 6])

In [18]:

w = np.random.randn(3,2)

In [19]:
w

array([[-0.51907262,  0.99955312],
       [-1.89622178, -3.13005564],
       [ 0.1841909 , -0.65295785]])

In [ ]:
np.random.seed(42)
print(np.random.rand(3))

[0.59865848 0.15601864 0.15599452]


Statistics for ML

In [26]:
data = np.array([10, 20, 30, 40, 50])

print(data.mean())
print(data.var())
print(data.std())


30.0
200.0
14.142135623730951


[[-1.22474487 -1.22474487]
 [ 1.22474487  1.22474487]
 [ 0.          0.        ]]
