In [2]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [60, 65, 70],
    [88, 92, 95],
    [50, 55, 58]
])



Tasks

Find average marks of each student

Find average marks of each subject

Find top scorer (row index)

Find students who scored more than 80 in all subjects

In [3]:
print(marks.mean(axis=1))

print(marks.mean(axis=0))

avg = (marks.mean(axis=1))
print(np.argmax(avg))

high_score = np.where(np.all(marks > 80 , axis = 1))[0]
print(high_score)



[84.33333333 65.         91.66666667 54.33333333]
[69.   74.25 78.25]
2
[2]


In [4]:
salaries = np.array([25000, 40000, 55000, 30000, 80000, 45000])

Tasks

Extract salaries above 40,000

Increase all salaries by 10%

Count how many employees earn more than average salary

Normalize salaries (mean = 0, std = 1)

In [5]:
print(salaries[salaries > 40000])

print(salaries + ( salaries * .1))

avg = salaries.mean()
print(salaries[salaries > avg])

mean = salaries.mean()
std = salaries.std()
normalize = ( salaries - mean ) / std
print(normalize)

[55000 80000 45000]
[27500. 44000. 60500. 33000. 88000. 49500.]
[55000 80000]
[-1.14950122 -0.32186034  0.50578054 -0.87362093  1.88518201 -0.04598005]


Tasks

Detect invalid values (-99)

Replace invalid values with mean of valid readings

Find min & max temperature

Standardize the cleaned sensor data

In [6]:
sensor = np.array([22.5, 23.0, -99.0, 24.1, 23.8, -99.0, 25.0])

In [9]:
invalid = sensor == -99
print(invalid)

valid_mean = sensor[~invalid].mean()
copy = valid_mean
sensor[invalid] = valid_mean
print(sensor)

sensor_standardized = (
    sensor - sensor.mean()
) / sensor.std()

print(sensor_standardized)


[False False  True False False  True False]
[22.5  23.   23.68 24.1  23.8  23.68 25.  ]
[-1.60408007 -0.92438512  0.          0.57094375  0.16312679  0.
  1.79439465]


In [8]:
data = np.array([
    [25, 50000, 1],
    [30, 60000, 0],
    [22, 45000, 1],
    [35, 80000, 0]
])


Tasks

Separate features (X) and target (y)

Extract only age & salary

Find average age of people who purchased

Normalize only the feature matrix

In [24]:
X = data[:,:2]
print(X)
Y = data[:,2]
print(Y)

age = data[:,0]
print(age)
salary = data[:,1]
print(salary)

mask = data[:,2] == 1
avg = data[mask,0].mean()
print(avg)

normaliz = ( X - X.mean(axis=0)) / X.std(axis=0)
print(normaliz)

[[   25 50000]
 [   30 60000]
 [   22 45000]
 [   35 80000]]
[1 0 1 0]
[25 30 22 35]
[50000 60000 45000 80000]
23.5
[[-0.60609153 -0.65275337]
 [ 0.40406102  0.09325048]
 [-1.21218305 -1.02575529]
 [ 1.41421356  1.58525817]]
